export enum ERole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  HEAD = 'HEAD',
  LEAD_MASTER = 'LEAD_MASTER',
  MASTER = 'MASTER',
  DETAIL_MASTER = 'DETAIL_MASTER',
  PACKER = 'PACKER',
}

export enum EWorkshop {
  W_Management = 'Управление',
  W_LPC4 = 'ЛПЦ-4',
  W_LPC5 = 'ЛПЦ-5',
  W_LPC7 = 'ЛПЦ-7',
  W_LPC8 = 'ЛПЦ-8',
  W_LPC10 = 'ЛПЦ-10',
  W_LPC11 = 'ЛПЦ-11',
  W_PMP_North = 'ПМП (северный блок)',
  W_PMP_South = 'ПМП (южный блок)',
  W_UVS_LPC4 = 'УВС ЛПЦ-4',
  W_CentralWarehouse = 'Центральный склад',
}

export enum ESchedule {
  S_5B1 = '5-Б-1',
  S_2A = '2-А',
  S_9 = '9',
  S_2 = '2',
}

export enum EAttendanceCode {
  A = 'А',
  BJ = 'БЖ',
  BJC = 'БЖЧ',
  V = 'В',
  VZ = 'ВЗ',
  VP = 'ВП',
  VPA = 'ВПА',
  VPP = 'ВПП',
  VPR = 'ВПР',
  GIA = 'ГИА',
  GS = 'ГС',
  GC = 'ГЧ',
  D = 'Д',
  DD = 'ДД',
  DI = 'ДИ',
  DND = 'ДНД',
  DO = 'ДО',
  DSR = 'ДСР',
  DU = 'ДУ',
  ZB = 'ЗБ',
  K = 'К',
  KO = 'КО',
  KOT = 'КОТ',
  KOC = 'КОЧ',
  KU = 'КУ',
  KUV = 'КУВ',
  KUD = 'КУД',
  LA = 'ЛА',
  M = 'М',
  MO = 'МО',
  NB = 'НБ',
  ND = 'НД',
  NN = 'НН',
  NS = 'НС',
  OA = 'ОА',
  OD = 'ОД',
  OJ = 'ОЖ',
  OI = 'ОИ',
  OL = 'ОЛ',
  OP = 'ОП',
  ORS = 'ОРС',
  ORC = 'ОРЧ',
  OS = 'ОС',
  OSR = 'ОСР',
  OT = 'ОТ',
  OTD = 'ОТД',
  OTR = 'ОТР',
  OTC = 'ОТЧ',
  OU = 'ОУ',
  OUT = 'ОУТ',
  OC = 'ОЧ',
  P = 'П',
  PV = 'ПВ',
  PM = 'ПМ',
  PR = 'ПР',
  PTD = 'ПТД',
  PU = 'ПУ',
  R = 'Р',
  RV = 'РВ',
  RDC = 'РДЧ',
  RN = 'РН',
  S = 'С',
  SD = 'СД',
  SDN = 'СДН',
  SI = 'СИ',
  SN = 'СН',
  SC = 'СЧ',
  U = 'У',
  UD = 'УД',
  UC = 'УЧ',
  HS = 'ХС',
  HC = 'ХЧ',
  CI = 'ЧИ',
  Y = 'Я',
}

export enum EUnit {
  // ЛПЦ-5
  LPC_4 = 'ЛПЦ-4',
  NTA = 'НТА',
  NTA_K = 'НТА-К',
  APR_2 = 'АПР-2',
  APR_3 = 'АПР-3',
  APR_4 = 'АПР-4',
  APR_5 = 'АПР-5',
  APR_8 = 'АПР-8',
  APR_9 = 'АПР-9',

  // ЛПЦ-11
  STAN = 'СТАН-2000',
  ANGZ = 'АНГЦ',
  ANO = 'АНО-ГЦ',
  AI = 'АИ',
  ANGZ_3 = 'АНГЦ-3',
  LUM = 'ЛУМ',
}

export enum ERailway {
  // ЛПЦ-11
  TUPIC_6 = 'Тупик 6',
  TUPIC_7 = 'Тупик 7',
  TUPIC_8 = 'Тупик 8',
  TUPIC_10 = 'Тупик 10',

  // ЛПЦ-5
  TUPIC_10_1 = 'Тупик 10/1',
  TUPIC_10_2 = 'Тупик 10/2',
  TUPIC_12 = 'Тупик 12',
}
